### ISSUE TITLE
Fork some of your scripts to git-extras

### ISSUE THREAD

**Issue by bric3** [Osse/git-scripts#3]
Hi,

I came around your `git-brv` script, and quite liked it. I believe it could be promoted way more in the git-extras project which has a bigger visibility, and has already various distribution channels like homebrew (for mac users), and benefit from some integration e.g. in [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/git-extras).

However the git-extras owner would like your permission to do so, which seems right anyway?

Issue in question https://github.com/tj/git-extras/issues/770

That would be awesome if you could feed us your opinion on the matter.
Thanks a lot in advance !

**Comment by Osse** [comment]
Sorry for the delay. No problemo. I've commented on the other issue as well.
